apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: react-express-api-server
spec:
  replicas: 5
  template:
    metadata:
      labels:
        name: react-express-server
    spec:
      containers:
      - name: react-express-server
        image: nepomucen/react-server-demo:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: react-express-server-service
  labels:
    app: react-express
spec:
  type: ClusterIP
  ports:
  - port: 5000
    protocol: TCP
  selector:
    name: react-express-server
